### ISSUE TITLE
About the GloVe embedding

### ISSUE THREAD

**Issue by shadowkiller33** [qianc62/Corsair#2]
Wonderful work! And I have a little question.

Is the GloVe embedding the one pre-trained on Wiki or Twitter? Could you please offer a link for w2v files?

**Comment by qianc62** [comment]
Thanks! We use GloVe pretrained on Wikipedia 2014 + Gigaword 5; please see https://nlp.stanford.edu/projects/glove/ for the file.

**Comment by shadowkiller33** [comment]
Thanks a lot^^
